development:
  adapter: mysql
  database: importer_dev
  username: root 
  password:        

production:
  adapter: mysql
  database: importer_dev
  username: root 
  password:  
  encoding: utf8
          
test:
  adapter: mysql
  database: importer_test
  username: root
  password:
  encoding: utf8
